### ISSUE TITLE
取消事件的bug

### ISSUE THREAD

**Issue by KevinCN511** [lin-xin/notepad#1]
问题重现步骤：

- [ ] 新建2个事件
- [ ] 删除第一个事件 (event.id = 0)
- [ ] 再新建1个事件
- [ ] 点击取消列表中的第二个事件

这时实际取消的是列表中的第一个事件，看代码发现，是由于addevent方法中的新id算法造成的。
`
ADDEVENT(states,obj){
        **let len = states.event.length + 1;**
        obj.items.id = len;
        states.event.unshift(obj.items);
        local.set(states.event);
    }
`

**Comment by lin-xin** [comment]
已修复，addevent方法中的新id算法改为在states中存储一个最大id，每次添加一次都 +1，类似数据库的id递增。
