### ISSUE TITLE
项目不能运行

### ISSUE THREAD

**Issue by rowthan** [lin-xin/notepad#2]
- 项目依赖项感觉过多额，能不能精简一下，光是安装就花了好几分钟。
- 启动不起来啊，node npm 都是高版本
![image](https://cloud.githubusercontent.com/assets/12638456/22831357/0eddc176-efe5-11e6-9419-0e2b8156d802.png)
- 既然是一个简单的记录功能，为什么不做成html单机版的呢，使用它还要启动一个node服务不是有点得不偿失吗。

**Comment by lin-xin** [comment]
是node-sass安装失败吗，是的话，可以先安装cnpm，再用cnpm安装node-sass，我这边在其他目录下clone下来之后安装了依赖，是可以启动的。
启动node服务只是方便开发，得与失在于个人之间。

**Comment by rowthan** [comment]
不是依赖安装失败的原因 是项目本身问题。你node版本是多少哦 怕不是4.0.0以上就可以哦 看到你代码里面用到了箭头函数 高版本node才支持吧。

**Comment by rowthan** [comment]
![image](https://cloud.githubusercontent.com/assets/12638456/22930618/1ba6c834-f2fc-11e6-9840-d291d799476c.png)
好吧 我放弃了 事实证明也不是版本问题（已经升级到lts最新版）

**Comment by lin-xin** [comment]
你这问题是你的8080端口被占用了

**Comment by lin-xin** [comment]
这是你的端口被占用，不关程序的问题。你可以搜一下这个错误Error: listen EACCES 0.0.0.0:8080查找解决方法。
