### ISSUE TITLE
中文输入法状态输入英文单词 Enter 会触发提交

### ISSUE THREAD

**Issue by laozhu** [lin-xin/notepad#5]
![jietu](https://user-images.githubusercontent.com/1212457/28097685-4cbb060e-66e4-11e7-994c-fad8e7efc345.gif)

也许是使用习惯问题，我一般在中文状态下直接打英文，不切换的，我用的 sogou 输入法。

**Comment by lin-xin** [comment]
@laozhu 确实是监听enter事件就会触发提交。但是你这习惯，还真是体验不好

**Comment by laozhu** [comment]
@lin-xin 其实如果用数字选择候选词就没这个问题了，确实是习惯了，不知道有没有办法优化呢。

**Comment by nb5p** [comment]
> @laozhu 确实是监听enter事件就会触发提交。但是你这习惯，还真是体验不好

此问题为macOS输入法框架的Bug，目前无法解决。具体原因是输入法选词框只能捕获Enter键按下事件，Enter键抬起动作直接传递给了下方的应用程序。而在其他平台输入法框检测到按下Enter之后，将不会把Enter的抬起事件发送到光标所在应用程序。
